name: Node CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: lint
        run: |
          yarn
          yarn lint
        
  test:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install xvfb
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y xvfb graphicsmagick libsecret-1-dev gnome-keyring
        npm install -g xvfb-maybe
        eval $(dbus-launch --sh-syntax);
    - name: npm install and test
      run: |
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        yarn
        yarn test
      env:
        CI: true
        DISPLAY: :99.0
        NO_AT_BRIDGE: 1
